---
functional:
  - требование 1 у пользователя есть возможность участвовать в игре без регистрации на сайте
  - требование 2 пользователь должен иметь возможность зарегистрироваться на сайте
  - требование 3 пользователь должен иметь возможность авторизоваться на сайте
  - требование 4 пользователь должен иметь возможность создавать игру самостоятельно
  - требование 5 пользователь должен иметь возможность выбрать язык из таких, как JavaScript, PHP, Python и Ruby
  - требование 6 пользователь должен иметь возможность выбора участвовать в игре с другом, с другим пользователем, с ботом
  - требование 7 пользователь должен иметь возможность пригласить друга в открытую игру по направленной ссылке
  - требование 8 пользователь должен иметь возможность отменить приглашение другу в открытой игре
  - требование 9 пользователь должен иметь возможность зайти в качестве зрителя в запущенную игру
  - требование 10 пользователь должен иметь возможность во время поединка одновременно видеть свой код и код соперника в режиме он-лайн
  - требование 11 пользователь имеет возможность проверить свое решение с помощью кнопки "check", количество попыток проверки неограниченно
  - требование 12 если вдруг один из игроков вылетел из игры, у второго игрока должна быть возможность продолжать играть
  - требование 13 если вдруг один из игроков вылетел из игры, у него должна быть возможность переподключиться в игру
  - требование 14 если вдруг один из игроков вылетел из игры, при переподключении игрока, Игра должна длиться неограниченное время
  - требование 15 оба игрока должны иметь возможность видеть высвечивающееся модальное окно, где написано, кто является победителем этой игры, когда один из игроков находит верное решение
  - требование 16 победитель в игре должен иметь возможность выйти из игры по нажатию кнопки "exit", либо остаться и посмотреть ещё раз на свой код
  - требование 17 соперник должен иметь возможность выйти из игры, либо доиграть до конца
  - требование 18 когда оба игрока вышли, игра считается полностью законченной и должна удаляться из памяти
non-functional:
  - требование 19 сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - требование 20 сайт должен быть безопасным и защищать данные пользователя
  - требование 21 сайт должен иметь возможность обрабатывать большое количество трафика
  - требование 22 сайт должен быть совместим с последними версиями браузеров
implicit:
  - требование 23 должна быть возможность следить за открытыми играми без посещения сайта, если установить расширение для Chrome
  - требование 24 сайт должен быть простым и понятным для пользователя
